# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: savour_rpc/keylocker.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='savour_rpc/keylocker.proto',
  package='savour_rpc.keylocker',
  syntax='proto3',
  serialized_options=b'\n\026group.savour.keylockerZ\021./proto/keylocker',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1asavour_rpc/keylocker.proto\x12\x14savour_rpc.keylocker\"$\n\tSocialKey\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\t\"I\n\x0fSupportChainReq\x12\x16\n\x0e\x63onsumer_token\x18\x01 \x01(\t\x12\r\n\x05\x63hain\x18\x02 \x01(\t\x12\x0f\n\x07network\x18\x03 \x01(\t\"_\n\x0fSupportChainRep\x12.\n\x04\x63ode\x18\x01 \x01(\x0e\x32 .savour_rpc.keylocker.ReturnCode\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0f\n\x07support\x18\x03 \x01(\x08\"\x81\x01\n\x0fSetSocialKeyReq\x12\x16\n\x0e\x63onsumer_token\x18\x01 \x01(\t\x12\r\n\x05\x63hain\x18\x02 \x01(\t\x12\x13\n\x0bwallet_uuid\x18\x03 \x01(\t\x12\x0b\n\x03key\x18\x04 \x01(\t\x12\x10\n\x08password\x18\x05 \x01(\t\x12\x13\n\x0bsocial_code\x18\x06 \x01(\t\"\xa1\x01\n\x0fSetSocialKeyRep\x12.\n\x04\x63ode\x18\x01 \x01(\x0e\x32 .savour_rpc.keylocker.ReturnCode\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0b\n\x03pub\x18\x03 \x01(\t\x12\x0c\n\x04priv\x18\x04 \x01(\t\x12\x12\n\ncrypto_way\x18\x05 \x01(\t\x12\x10\n\x08\x66ile_cid\x18\x06 \x01(\t\x12\x10\n\x08\x63ontract\x18\x07 \x01(\t\"_\n\x0fGetSocialKeyReq\x12\x16\n\x0e\x63onsumer_token\x18\x01 \x01(\t\x12\r\n\x05\x63hain\x18\x02 \x01(\t\x12\x13\n\x0bwallet_uuid\x18\x03 \x01(\t\x12\x10\n\x08\x66ile_cid\x18\x04 \x01(\t\"\x81\x01\n\x0fGetSocialKeyRep\x12.\n\x04\x63ode\x18\x01 \x01(\x0e\x32 .savour_rpc.keylocker.ReturnCode\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x31\n\x08key_list\x18\x03 \x03(\x0b\x32\x1f.savour_rpc.keylocker.SocialKey*$\n\nReturnCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x32\xb5\x02\n\x10LeyLockerService\x12\x61\n\x0fgetSupportChain\x12%.savour_rpc.keylocker.SupportChainReq\x1a%.savour_rpc.keylocker.SupportChainRep\"\x00\x12^\n\x0csetSocialKey\x12%.savour_rpc.keylocker.SetSocialKeyReq\x1a%.savour_rpc.keylocker.SetSocialKeyRep\"\x00\x12^\n\x0cgetSocialKey\x12%.savour_rpc.keylocker.GetSocialKeyReq\x1a%.savour_rpc.keylocker.GetSocialKeyRep\"\x00\x42+\n\x16group.savour.keylockerZ\x11./proto/keylockerb\x06proto3'
)

_RETURNCODE = _descriptor.EnumDescriptor(
  name='ReturnCode',
  full_name='savour_rpc.keylocker.ReturnCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=787,
  serialized_end=823,
)
_sym_db.RegisterEnumDescriptor(_RETURNCODE)

ReturnCode = enum_type_wrapper.EnumTypeWrapper(_RETURNCODE)
SUCCESS = 0
ERROR = 1



_SOCIALKEY = _descriptor.Descriptor(
  name='SocialKey',
  full_name='savour_rpc.keylocker.SocialKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='savour_rpc.keylocker.SocialKey.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='savour_rpc.keylocker.SocialKey.key', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=88,
)


_SUPPORTCHAINREQ = _descriptor.Descriptor(
  name='SupportChainReq',
  full_name='savour_rpc.keylocker.SupportChainReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='consumer_token', full_name='savour_rpc.keylocker.SupportChainReq.consumer_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chain', full_name='savour_rpc.keylocker.SupportChainReq.chain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='network', full_name='savour_rpc.keylocker.SupportChainReq.network', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=163,
)


_SUPPORTCHAINREP = _descriptor.Descriptor(
  name='SupportChainRep',
  full_name='savour_rpc.keylocker.SupportChainRep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='savour_rpc.keylocker.SupportChainRep.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='savour_rpc.keylocker.SupportChainRep.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='support', full_name='savour_rpc.keylocker.SupportChainRep.support', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=260,
)


_SETSOCIALKEYREQ = _descriptor.Descriptor(
  name='SetSocialKeyReq',
  full_name='savour_rpc.keylocker.SetSocialKeyReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='consumer_token', full_name='savour_rpc.keylocker.SetSocialKeyReq.consumer_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chain', full_name='savour_rpc.keylocker.SetSocialKeyReq.chain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wallet_uuid', full_name='savour_rpc.keylocker.SetSocialKeyReq.wallet_uuid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='savour_rpc.keylocker.SetSocialKeyReq.key', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='savour_rpc.keylocker.SetSocialKeyReq.password', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='social_code', full_name='savour_rpc.keylocker.SetSocialKeyReq.social_code', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=392,
)


_SETSOCIALKEYREP = _descriptor.Descriptor(
  name='SetSocialKeyRep',
  full_name='savour_rpc.keylocker.SetSocialKeyRep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='savour_rpc.keylocker.SetSocialKeyRep.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='savour_rpc.keylocker.SetSocialKeyRep.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pub', full_name='savour_rpc.keylocker.SetSocialKeyRep.pub', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='priv', full_name='savour_rpc.keylocker.SetSocialKeyRep.priv', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='crypto_way', full_name='savour_rpc.keylocker.SetSocialKeyRep.crypto_way', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_cid', full_name='savour_rpc.keylocker.SetSocialKeyRep.file_cid', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contract', full_name='savour_rpc.keylocker.SetSocialKeyRep.contract', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=395,
  serialized_end=556,
)


_GETSOCIALKEYREQ = _descriptor.Descriptor(
  name='GetSocialKeyReq',
  full_name='savour_rpc.keylocker.GetSocialKeyReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='consumer_token', full_name='savour_rpc.keylocker.GetSocialKeyReq.consumer_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chain', full_name='savour_rpc.keylocker.GetSocialKeyReq.chain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wallet_uuid', full_name='savour_rpc.keylocker.GetSocialKeyReq.wallet_uuid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_cid', full_name='savour_rpc.keylocker.GetSocialKeyReq.file_cid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=558,
  serialized_end=653,
)


_GETSOCIALKEYREP = _descriptor.Descriptor(
  name='GetSocialKeyRep',
  full_name='savour_rpc.keylocker.GetSocialKeyRep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='savour_rpc.keylocker.GetSocialKeyRep.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='savour_rpc.keylocker.GetSocialKeyRep.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_list', full_name='savour_rpc.keylocker.GetSocialKeyRep.key_list', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=656,
  serialized_end=785,
)

_SUPPORTCHAINREP.fields_by_name['code'].enum_type = _RETURNCODE
_SETSOCIALKEYREP.fields_by_name['code'].enum_type = _RETURNCODE
_GETSOCIALKEYREP.fields_by_name['code'].enum_type = _RETURNCODE
_GETSOCIALKEYREP.fields_by_name['key_list'].message_type = _SOCIALKEY
DESCRIPTOR.message_types_by_name['SocialKey'] = _SOCIALKEY
DESCRIPTOR.message_types_by_name['SupportChainReq'] = _SUPPORTCHAINREQ
DESCRIPTOR.message_types_by_name['SupportChainRep'] = _SUPPORTCHAINREP
DESCRIPTOR.message_types_by_name['SetSocialKeyReq'] = _SETSOCIALKEYREQ
DESCRIPTOR.message_types_by_name['SetSocialKeyRep'] = _SETSOCIALKEYREP
DESCRIPTOR.message_types_by_name['GetSocialKeyReq'] = _GETSOCIALKEYREQ
DESCRIPTOR.message_types_by_name['GetSocialKeyRep'] = _GETSOCIALKEYREP
DESCRIPTOR.enum_types_by_name['ReturnCode'] = _RETURNCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SocialKey = _reflection.GeneratedProtocolMessageType('SocialKey', (_message.Message,), {
  'DESCRIPTOR' : _SOCIALKEY,
  '__module__' : 'savour_rpc.keylocker_pb2'
  # @@protoc_insertion_point(class_scope:savour_rpc.keylocker.SocialKey)
  })
_sym_db.RegisterMessage(SocialKey)

SupportChainReq = _reflection.GeneratedProtocolMessageType('SupportChainReq', (_message.Message,), {
  'DESCRIPTOR' : _SUPPORTCHAINREQ,
  '__module__' : 'savour_rpc.keylocker_pb2'
  # @@protoc_insertion_point(class_scope:savour_rpc.keylocker.SupportChainReq)
  })
_sym_db.RegisterMessage(SupportChainReq)

SupportChainRep = _reflection.GeneratedProtocolMessageType('SupportChainRep', (_message.Message,), {
  'DESCRIPTOR' : _SUPPORTCHAINREP,
  '__module__' : 'savour_rpc.keylocker_pb2'
  # @@protoc_insertion_point(class_scope:savour_rpc.keylocker.SupportChainRep)
  })
_sym_db.RegisterMessage(SupportChainRep)

SetSocialKeyReq = _reflection.GeneratedProtocolMessageType('SetSocialKeyReq', (_message.Message,), {
  'DESCRIPTOR' : _SETSOCIALKEYREQ,
  '__module__' : 'savour_rpc.keylocker_pb2'
  # @@protoc_insertion_point(class_scope:savour_rpc.keylocker.SetSocialKeyReq)
  })
_sym_db.RegisterMessage(SetSocialKeyReq)

SetSocialKeyRep = _reflection.GeneratedProtocolMessageType('SetSocialKeyRep', (_message.Message,), {
  'DESCRIPTOR' : _SETSOCIALKEYREP,
  '__module__' : 'savour_rpc.keylocker_pb2'
  # @@protoc_insertion_point(class_scope:savour_rpc.keylocker.SetSocialKeyRep)
  })
_sym_db.RegisterMessage(SetSocialKeyRep)

GetSocialKeyReq = _reflection.GeneratedProtocolMessageType('GetSocialKeyReq', (_message.Message,), {
  'DESCRIPTOR' : _GETSOCIALKEYREQ,
  '__module__' : 'savour_rpc.keylocker_pb2'
  # @@protoc_insertion_point(class_scope:savour_rpc.keylocker.GetSocialKeyReq)
  })
_sym_db.RegisterMessage(GetSocialKeyReq)

GetSocialKeyRep = _reflection.GeneratedProtocolMessageType('GetSocialKeyRep', (_message.Message,), {
  'DESCRIPTOR' : _GETSOCIALKEYREP,
  '__module__' : 'savour_rpc.keylocker_pb2'
  # @@protoc_insertion_point(class_scope:savour_rpc.keylocker.GetSocialKeyRep)
  })
_sym_db.RegisterMessage(GetSocialKeyRep)


DESCRIPTOR._options = None

_LEYLOCKERSERVICE = _descriptor.ServiceDescriptor(
  name='LeyLockerService',
  full_name='savour_rpc.keylocker.LeyLockerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=826,
  serialized_end=1135,
  methods=[
  _descriptor.MethodDescriptor(
    name='getSupportChain',
    full_name='savour_rpc.keylocker.LeyLockerService.getSupportChain',
    index=0,
    containing_service=None,
    input_type=_SUPPORTCHAINREQ,
    output_type=_SUPPORTCHAINREP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='setSocialKey',
    full_name='savour_rpc.keylocker.LeyLockerService.setSocialKey',
    index=1,
    containing_service=None,
    input_type=_SETSOCIALKEYREQ,
    output_type=_SETSOCIALKEYREP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getSocialKey',
    full_name='savour_rpc.keylocker.LeyLockerService.getSocialKey',
    index=2,
    containing_service=None,
    input_type=_GETSOCIALKEYREQ,
    output_type=_GETSOCIALKEYREP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LEYLOCKERSERVICE)

DESCRIPTOR.services_by_name['LeyLockerService'] = _LEYLOCKERSERVICE

# @@protoc_insertion_point(module_scope)
