// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: savourrpc/keylocker.proto

package keylocker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChaineyeServiceClient is the client API for ChaineyeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChaineyeServiceClient interface {
	SetSocialKey(ctx context.Context, in *SetSocialKeyReq, opts ...grpc.CallOption) (*SetSocialKeyRep, error)
	GetSocialKey(ctx context.Context, in *GetSocialKeyReq, opts ...grpc.CallOption) (*GetSocialKeyRep, error)
}

type chaineyeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChaineyeServiceClient(cc grpc.ClientConnInterface) ChaineyeServiceClient {
	return &chaineyeServiceClient{cc}
}

func (c *chaineyeServiceClient) SetSocialKey(ctx context.Context, in *SetSocialKeyReq, opts ...grpc.CallOption) (*SetSocialKeyRep, error) {
	out := new(SetSocialKeyRep)
	err := c.cc.Invoke(ctx, "/savourrpc.keylocker.ChaineyeService/setSocialKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaineyeServiceClient) GetSocialKey(ctx context.Context, in *GetSocialKeyReq, opts ...grpc.CallOption) (*GetSocialKeyRep, error) {
	out := new(GetSocialKeyRep)
	err := c.cc.Invoke(ctx, "/savourrpc.keylocker.ChaineyeService/getSocialKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChaineyeServiceServer is the server API for ChaineyeService service.
// All implementations must embed UnimplementedChaineyeServiceServer
// for forward compatibility
type ChaineyeServiceServer interface {
	SetSocialKey(context.Context, *SetSocialKeyReq) (*SetSocialKeyRep, error)
	GetSocialKey(context.Context, *GetSocialKeyReq) (*GetSocialKeyRep, error)
	mustEmbedUnimplementedChaineyeServiceServer()
}

// UnimplementedChaineyeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChaineyeServiceServer struct {
}

func (UnimplementedChaineyeServiceServer) SetSocialKey(context.Context, *SetSocialKeyReq) (*SetSocialKeyRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSocialKey not implemented")
}
func (UnimplementedChaineyeServiceServer) GetSocialKey(context.Context, *GetSocialKeyReq) (*GetSocialKeyRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSocialKey not implemented")
}
func (UnimplementedChaineyeServiceServer) mustEmbedUnimplementedChaineyeServiceServer() {}

// UnsafeChaineyeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChaineyeServiceServer will
// result in compilation errors.
type UnsafeChaineyeServiceServer interface {
	mustEmbedUnimplementedChaineyeServiceServer()
}

func RegisterChaineyeServiceServer(s grpc.ServiceRegistrar, srv ChaineyeServiceServer) {
	s.RegisterService(&ChaineyeService_ServiceDesc, srv)
}

func _ChaineyeService_SetSocialKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSocialKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaineyeServiceServer).SetSocialKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.keylocker.ChaineyeService/setSocialKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaineyeServiceServer).SetSocialKey(ctx, req.(*SetSocialKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaineyeService_GetSocialKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSocialKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaineyeServiceServer).GetSocialKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.keylocker.ChaineyeService/getSocialKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaineyeServiceServer).GetSocialKey(ctx, req.(*GetSocialKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ChaineyeService_ServiceDesc is the grpc.ServiceDesc for ChaineyeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChaineyeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "savourrpc.keylocker.ChaineyeService",
	HandlerType: (*ChaineyeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "setSocialKey",
			Handler:    _ChaineyeService_SetSocialKey_Handler,
		},
		{
			MethodName: "getSocialKey",
			Handler:    _ChaineyeService_GetSocialKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "savourrpc/keylocker.proto",
}
