// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: savourrpc/market.proto

package market

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PriceServiceClient is the client API for PriceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PriceServiceClient interface {
	GetSymbols(ctx context.Context, in *SymbolRequest, opts ...grpc.CallOption) (*SymbolResponse, error)
	GetSymbolPrices(ctx context.Context, in *SymbolPriceRequest, opts ...grpc.CallOption) (*SymbolPriceResponse, error)
	GetStableCoins(ctx context.Context, in *StableCoinRequest, opts ...grpc.CallOption) (*StableCoinResponse, error)
	GetStableCoinPrice(ctx context.Context, in *StableCoinPriceRequest, opts ...grpc.CallOption) (*StableCoinPriceResponse, error)
}

type priceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPriceServiceClient(cc grpc.ClientConnInterface) PriceServiceClient {
	return &priceServiceClient{cc}
}

func (c *priceServiceClient) GetSymbols(ctx context.Context, in *SymbolRequest, opts ...grpc.CallOption) (*SymbolResponse, error) {
	out := new(SymbolResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.market.PriceService/getSymbols", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceServiceClient) GetSymbolPrices(ctx context.Context, in *SymbolPriceRequest, opts ...grpc.CallOption) (*SymbolPriceResponse, error) {
	out := new(SymbolPriceResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.market.PriceService/getSymbolPrices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceServiceClient) GetStableCoins(ctx context.Context, in *StableCoinRequest, opts ...grpc.CallOption) (*StableCoinResponse, error) {
	out := new(StableCoinResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.market.PriceService/getStableCoins", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceServiceClient) GetStableCoinPrice(ctx context.Context, in *StableCoinPriceRequest, opts ...grpc.CallOption) (*StableCoinPriceResponse, error) {
	out := new(StableCoinPriceResponse)
	err := c.cc.Invoke(ctx, "/savourrpc.market.PriceService/getStableCoinPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PriceServiceServer is the server API for PriceService service.
// All implementations must embed UnimplementedPriceServiceServer
// for forward compatibility
type PriceServiceServer interface {
	GetSymbols(context.Context, *SymbolRequest) (*SymbolResponse, error)
	GetSymbolPrices(context.Context, *SymbolPriceRequest) (*SymbolPriceResponse, error)
	GetStableCoins(context.Context, *StableCoinRequest) (*StableCoinResponse, error)
	GetStableCoinPrice(context.Context, *StableCoinPriceRequest) (*StableCoinPriceResponse, error)
	mustEmbedUnimplementedPriceServiceServer()
}

// UnimplementedPriceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPriceServiceServer struct {
}

func (UnimplementedPriceServiceServer) GetSymbols(context.Context, *SymbolRequest) (*SymbolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSymbols not implemented")
}
func (UnimplementedPriceServiceServer) GetSymbolPrices(context.Context, *SymbolPriceRequest) (*SymbolPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSymbolPrices not implemented")
}
func (UnimplementedPriceServiceServer) GetStableCoins(context.Context, *StableCoinRequest) (*StableCoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStableCoins not implemented")
}
func (UnimplementedPriceServiceServer) GetStableCoinPrice(context.Context, *StableCoinPriceRequest) (*StableCoinPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStableCoinPrice not implemented")
}
func (UnimplementedPriceServiceServer) mustEmbedUnimplementedPriceServiceServer() {}

// UnsafePriceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PriceServiceServer will
// result in compilation errors.
type UnsafePriceServiceServer interface {
	mustEmbedUnimplementedPriceServiceServer()
}

func RegisterPriceServiceServer(s grpc.ServiceRegistrar, srv PriceServiceServer) {
	s.RegisterService(&PriceService_ServiceDesc, srv)
}

func _PriceService_GetSymbols_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SymbolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceServiceServer).GetSymbols(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.market.PriceService/getSymbols",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceServiceServer).GetSymbols(ctx, req.(*SymbolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PriceService_GetSymbolPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SymbolPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceServiceServer).GetSymbolPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.market.PriceService/getSymbolPrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceServiceServer).GetSymbolPrices(ctx, req.(*SymbolPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PriceService_GetStableCoins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StableCoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceServiceServer).GetStableCoins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.market.PriceService/getStableCoins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceServiceServer).GetStableCoins(ctx, req.(*StableCoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PriceService_GetStableCoinPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StableCoinPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceServiceServer).GetStableCoinPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/savourrpc.market.PriceService/getStableCoinPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceServiceServer).GetStableCoinPrice(ctx, req.(*StableCoinPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PriceService_ServiceDesc is the grpc.ServiceDesc for PriceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PriceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "savourrpc.market.PriceService",
	HandlerType: (*PriceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getSymbols",
			Handler:    _PriceService_GetSymbols_Handler,
		},
		{
			MethodName: "getSymbolPrices",
			Handler:    _PriceService_GetSymbolPrices_Handler,
		},
		{
			MethodName: "getStableCoins",
			Handler:    _PriceService_GetStableCoins_Handler,
		},
		{
			MethodName: "getStableCoinPrice",
			Handler:    _PriceService_GetStableCoinPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "savourrpc/market.proto",
}
