# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: savourrpc/chaineye.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import savourrpc.common_pb2
import savourrpc.chaineye_pb2


class ChaineyeServiceBase(abc.ABC):

    @abc.abstractmethod
    async def getArticleCat(self, stream: 'grpclib.server.Stream[savourrpc.chaineye_pb2.ArticleCatReq, savourrpc.chaineye_pb2.ArticleCatRep]') -> None:
        pass

    @abc.abstractmethod
    async def getArticleList(self, stream: 'grpclib.server.Stream[savourrpc.chaineye_pb2.ArticleListReq, savourrpc.chaineye_pb2.ArticleListRep]') -> None:
        pass

    @abc.abstractmethod
    async def getArticleDetail(self, stream: 'grpclib.server.Stream[savourrpc.chaineye_pb2.ArticleDetailReq, savourrpc.chaineye_pb2.ArticleDetailRep]') -> None:
        pass

    @abc.abstractmethod
    async def getCommentList(self, stream: 'grpclib.server.Stream[savourrpc.chaineye_pb2.CommentListReq, savourrpc.chaineye_pb2.CommentListRep]') -> None:
        pass

    @abc.abstractmethod
    async def getLikeAddress(self, stream: 'grpclib.server.Stream[savourrpc.chaineye_pb2.AddressReq, savourrpc.chaineye_pb2.AddressRep]') -> None:
        pass

    @abc.abstractmethod
    async def likeArticle(self, stream: 'grpclib.server.Stream[savourrpc.chaineye_pb2.LikeReq, savourrpc.chaineye_pb2.LikeRep]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/savourrpc.chaineye.ChaineyeService/getArticleCat': grpclib.const.Handler(
                self.getArticleCat,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.chaineye_pb2.ArticleCatReq,
                savourrpc.chaineye_pb2.ArticleCatRep,
            ),
            '/savourrpc.chaineye.ChaineyeService/getArticleList': grpclib.const.Handler(
                self.getArticleList,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.chaineye_pb2.ArticleListReq,
                savourrpc.chaineye_pb2.ArticleListRep,
            ),
            '/savourrpc.chaineye.ChaineyeService/getArticleDetail': grpclib.const.Handler(
                self.getArticleDetail,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.chaineye_pb2.ArticleDetailReq,
                savourrpc.chaineye_pb2.ArticleDetailRep,
            ),
            '/savourrpc.chaineye.ChaineyeService/getCommentList': grpclib.const.Handler(
                self.getCommentList,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.chaineye_pb2.CommentListReq,
                savourrpc.chaineye_pb2.CommentListRep,
            ),
            '/savourrpc.chaineye.ChaineyeService/getLikeAddress': grpclib.const.Handler(
                self.getLikeAddress,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.chaineye_pb2.AddressReq,
                savourrpc.chaineye_pb2.AddressRep,
            ),
            '/savourrpc.chaineye.ChaineyeService/likeArticle': grpclib.const.Handler(
                self.likeArticle,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.chaineye_pb2.LikeReq,
                savourrpc.chaineye_pb2.LikeRep,
            ),
        }


class ChaineyeServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.getArticleCat = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.chaineye.ChaineyeService/getArticleCat',
            savourrpc.chaineye_pb2.ArticleCatReq,
            savourrpc.chaineye_pb2.ArticleCatRep,
        )
        self.getArticleList = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.chaineye.ChaineyeService/getArticleList',
            savourrpc.chaineye_pb2.ArticleListReq,
            savourrpc.chaineye_pb2.ArticleListRep,
        )
        self.getArticleDetail = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.chaineye.ChaineyeService/getArticleDetail',
            savourrpc.chaineye_pb2.ArticleDetailReq,
            savourrpc.chaineye_pb2.ArticleDetailRep,
        )
        self.getCommentList = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.chaineye.ChaineyeService/getCommentList',
            savourrpc.chaineye_pb2.CommentListReq,
            savourrpc.chaineye_pb2.CommentListRep,
        )
        self.getLikeAddress = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.chaineye.ChaineyeService/getLikeAddress',
            savourrpc.chaineye_pb2.AddressReq,
            savourrpc.chaineye_pb2.AddressRep,
        )
        self.likeArticle = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.chaineye.ChaineyeService/likeArticle',
            savourrpc.chaineye_pb2.LikeReq,
            savourrpc.chaineye_pb2.LikeRep,
        )
