# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: savourrpc/keylocker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from savourrpc import common_pb2 as savourrpc_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='savourrpc/keylocker.proto',
  package='savourrpc.keylocker',
  syntax='proto3',
  serialized_options=b'\n\027com.savourrpc.keylockerZ5git.savour.io/savour/savourrpc/go-savourrpc/keylocker',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19savourrpc/keylocker.proto\x12\x13savourrpc.keylocker\x1a\x16savourrpc/common.proto\"$\n\tSocialKey\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\t\"M\n\x13SupportChainRequest\x12\x16\n\x0e\x63onsumer_token\x18\x01 \x01(\t\x12\r\n\x05\x63hain\x18\x02 \x01(\t\x12\x0f\n\x07network\x18\x03 \x01(\t\"Y\n\x14SupportChainResponse\x12#\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x15.savourrpc.ReturnCode\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0f\n\x07support\x18\x03 \x01(\x08\"D\n\x0fSetSocialKeyReq\x12\x16\n\x0e\x63onsumer_token\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\t\"^\n\x0fSetSocialKeyRep\x12#\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x15.savourrpc.ReturnCode\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0b\n\x03pub\x18\x03 \x01(\t\x12\x0c\n\x04priv\x18\x04 \x01(\t\"7\n\x0fGetSocialKeyReq\x12\x16\n\x0e\x63onsumer_token\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\"u\n\x0fGetSocialKeyRep\x12#\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x15.savourrpc.ReturnCode\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x30\n\x08key_list\x18\x03 \x03(\x0b\x32\x1e.savourrpc.keylocker.SocialKey2\xb7\x02\n\x0f\x43haineyeService\x12h\n\x0fgetSupportChain\x12(.savourrpc.keylocker.SupportChainRequest\x1a).savourrpc.keylocker.SupportChainResponse\"\x00\x12\\\n\x0csetSocialKey\x12$.savourrpc.keylocker.SetSocialKeyReq\x1a$.savourrpc.keylocker.SetSocialKeyRep\"\x00\x12\\\n\x0cgetSocialKey\x12$.savourrpc.keylocker.GetSocialKeyReq\x1a$.savourrpc.keylocker.GetSocialKeyRep\"\x00\x42P\n\x17\x63om.savourrpc.keylockerZ5git.savour.io/savour/savourrpc/go-savourrpc/keylockerb\x06proto3'
  ,
  dependencies=[savourrpc_dot_common__pb2.DESCRIPTOR,])




_SOCIALKEY = _descriptor.Descriptor(
  name='SocialKey',
  full_name='savourrpc.keylocker.SocialKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='savourrpc.keylocker.SocialKey.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='savourrpc.keylocker.SocialKey.key', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=110,
)


_SUPPORTCHAINREQUEST = _descriptor.Descriptor(
  name='SupportChainRequest',
  full_name='savourrpc.keylocker.SupportChainRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='consumer_token', full_name='savourrpc.keylocker.SupportChainRequest.consumer_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chain', full_name='savourrpc.keylocker.SupportChainRequest.chain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='network', full_name='savourrpc.keylocker.SupportChainRequest.network', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=189,
)


_SUPPORTCHAINRESPONSE = _descriptor.Descriptor(
  name='SupportChainResponse',
  full_name='savourrpc.keylocker.SupportChainResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='savourrpc.keylocker.SupportChainResponse.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='savourrpc.keylocker.SupportChainResponse.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='support', full_name='savourrpc.keylocker.SupportChainResponse.support', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=280,
)


_SETSOCIALKEYREQ = _descriptor.Descriptor(
  name='SetSocialKeyReq',
  full_name='savourrpc.keylocker.SetSocialKeyReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='consumer_token', full_name='savourrpc.keylocker.SetSocialKeyReq.consumer_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='savourrpc.keylocker.SetSocialKeyReq.uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='savourrpc.keylocker.SetSocialKeyReq.key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=350,
)


_SETSOCIALKEYREP = _descriptor.Descriptor(
  name='SetSocialKeyRep',
  full_name='savourrpc.keylocker.SetSocialKeyRep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='savourrpc.keylocker.SetSocialKeyRep.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='savourrpc.keylocker.SetSocialKeyRep.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pub', full_name='savourrpc.keylocker.SetSocialKeyRep.pub', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='priv', full_name='savourrpc.keylocker.SetSocialKeyRep.priv', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=352,
  serialized_end=446,
)


_GETSOCIALKEYREQ = _descriptor.Descriptor(
  name='GetSocialKeyReq',
  full_name='savourrpc.keylocker.GetSocialKeyReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='consumer_token', full_name='savourrpc.keylocker.GetSocialKeyReq.consumer_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='savourrpc.keylocker.GetSocialKeyReq.uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=448,
  serialized_end=503,
)


_GETSOCIALKEYREP = _descriptor.Descriptor(
  name='GetSocialKeyRep',
  full_name='savourrpc.keylocker.GetSocialKeyRep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='savourrpc.keylocker.GetSocialKeyRep.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='savourrpc.keylocker.GetSocialKeyRep.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_list', full_name='savourrpc.keylocker.GetSocialKeyRep.key_list', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=505,
  serialized_end=622,
)

_SUPPORTCHAINRESPONSE.fields_by_name['code'].enum_type = savourrpc_dot_common__pb2._RETURNCODE
_SETSOCIALKEYREP.fields_by_name['code'].enum_type = savourrpc_dot_common__pb2._RETURNCODE
_GETSOCIALKEYREP.fields_by_name['code'].enum_type = savourrpc_dot_common__pb2._RETURNCODE
_GETSOCIALKEYREP.fields_by_name['key_list'].message_type = _SOCIALKEY
DESCRIPTOR.message_types_by_name['SocialKey'] = _SOCIALKEY
DESCRIPTOR.message_types_by_name['SupportChainRequest'] = _SUPPORTCHAINREQUEST
DESCRIPTOR.message_types_by_name['SupportChainResponse'] = _SUPPORTCHAINRESPONSE
DESCRIPTOR.message_types_by_name['SetSocialKeyReq'] = _SETSOCIALKEYREQ
DESCRIPTOR.message_types_by_name['SetSocialKeyRep'] = _SETSOCIALKEYREP
DESCRIPTOR.message_types_by_name['GetSocialKeyReq'] = _GETSOCIALKEYREQ
DESCRIPTOR.message_types_by_name['GetSocialKeyRep'] = _GETSOCIALKEYREP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SocialKey = _reflection.GeneratedProtocolMessageType('SocialKey', (_message.Message,), {
  'DESCRIPTOR' : _SOCIALKEY,
  '__module__' : 'savourrpc.keylocker_pb2'
  # @@protoc_insertion_point(class_scope:savourrpc.keylocker.SocialKey)
  })
_sym_db.RegisterMessage(SocialKey)

SupportChainRequest = _reflection.GeneratedProtocolMessageType('SupportChainRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUPPORTCHAINREQUEST,
  '__module__' : 'savourrpc.keylocker_pb2'
  # @@protoc_insertion_point(class_scope:savourrpc.keylocker.SupportChainRequest)
  })
_sym_db.RegisterMessage(SupportChainRequest)

SupportChainResponse = _reflection.GeneratedProtocolMessageType('SupportChainResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUPPORTCHAINRESPONSE,
  '__module__' : 'savourrpc.keylocker_pb2'
  # @@protoc_insertion_point(class_scope:savourrpc.keylocker.SupportChainResponse)
  })
_sym_db.RegisterMessage(SupportChainResponse)

SetSocialKeyReq = _reflection.GeneratedProtocolMessageType('SetSocialKeyReq', (_message.Message,), {
  'DESCRIPTOR' : _SETSOCIALKEYREQ,
  '__module__' : 'savourrpc.keylocker_pb2'
  # @@protoc_insertion_point(class_scope:savourrpc.keylocker.SetSocialKeyReq)
  })
_sym_db.RegisterMessage(SetSocialKeyReq)

SetSocialKeyRep = _reflection.GeneratedProtocolMessageType('SetSocialKeyRep', (_message.Message,), {
  'DESCRIPTOR' : _SETSOCIALKEYREP,
  '__module__' : 'savourrpc.keylocker_pb2'
  # @@protoc_insertion_point(class_scope:savourrpc.keylocker.SetSocialKeyRep)
  })
_sym_db.RegisterMessage(SetSocialKeyRep)

GetSocialKeyReq = _reflection.GeneratedProtocolMessageType('GetSocialKeyReq', (_message.Message,), {
  'DESCRIPTOR' : _GETSOCIALKEYREQ,
  '__module__' : 'savourrpc.keylocker_pb2'
  # @@protoc_insertion_point(class_scope:savourrpc.keylocker.GetSocialKeyReq)
  })
_sym_db.RegisterMessage(GetSocialKeyReq)

GetSocialKeyRep = _reflection.GeneratedProtocolMessageType('GetSocialKeyRep', (_message.Message,), {
  'DESCRIPTOR' : _GETSOCIALKEYREP,
  '__module__' : 'savourrpc.keylocker_pb2'
  # @@protoc_insertion_point(class_scope:savourrpc.keylocker.GetSocialKeyRep)
  })
_sym_db.RegisterMessage(GetSocialKeyRep)


DESCRIPTOR._options = None

_CHAINEYESERVICE = _descriptor.ServiceDescriptor(
  name='ChaineyeService',
  full_name='savourrpc.keylocker.ChaineyeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=625,
  serialized_end=936,
  methods=[
  _descriptor.MethodDescriptor(
    name='getSupportChain',
    full_name='savourrpc.keylocker.ChaineyeService.getSupportChain',
    index=0,
    containing_service=None,
    input_type=_SUPPORTCHAINREQUEST,
    output_type=_SUPPORTCHAINRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='setSocialKey',
    full_name='savourrpc.keylocker.ChaineyeService.setSocialKey',
    index=1,
    containing_service=None,
    input_type=_SETSOCIALKEYREQ,
    output_type=_SETSOCIALKEYREP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getSocialKey',
    full_name='savourrpc.keylocker.ChaineyeService.getSocialKey',
    index=2,
    containing_service=None,
    input_type=_GETSOCIALKEYREQ,
    output_type=_GETSOCIALKEYREP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHAINEYESERVICE)

DESCRIPTOR.services_by_name['ChaineyeService'] = _CHAINEYESERVICE

# @@protoc_insertion_point(module_scope)
