# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: savourrpc/market.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import savourrpc.common_pb2
import savourrpc.market_pb2


class PriceServiceBase(abc.ABC):

    @abc.abstractmethod
    async def getExchanges(self, stream: 'grpclib.server.Stream[savourrpc.market_pb2.ExchangeRequest, savourrpc.market_pb2.ExchangeResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getAssets(self, stream: 'grpclib.server.Stream[savourrpc.market_pb2.AssetRequest, savourrpc.market_pb2.AssetResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getSymbols(self, stream: 'grpclib.server.Stream[savourrpc.market_pb2.SymbolRequest, savourrpc.market_pb2.SymbolResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getSymbolPrices(self, stream: 'grpclib.server.Stream[savourrpc.market_pb2.SymbolPriceRequest, savourrpc.market_pb2.SymbolPriceResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getStableCoins(self, stream: 'grpclib.server.Stream[savourrpc.market_pb2.StableCoinRequest, savourrpc.market_pb2.StableCoinResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getStableCoinPrice(self, stream: 'grpclib.server.Stream[savourrpc.market_pb2.StableCoinPriceRequest, savourrpc.market_pb2.StableCoinPriceResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/savourrpc.market.PriceService/getExchanges': grpclib.const.Handler(
                self.getExchanges,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.market_pb2.ExchangeRequest,
                savourrpc.market_pb2.ExchangeResponse,
            ),
            '/savourrpc.market.PriceService/getAssets': grpclib.const.Handler(
                self.getAssets,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.market_pb2.AssetRequest,
                savourrpc.market_pb2.AssetResponse,
            ),
            '/savourrpc.market.PriceService/getSymbols': grpclib.const.Handler(
                self.getSymbols,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.market_pb2.SymbolRequest,
                savourrpc.market_pb2.SymbolResponse,
            ),
            '/savourrpc.market.PriceService/getSymbolPrices': grpclib.const.Handler(
                self.getSymbolPrices,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.market_pb2.SymbolPriceRequest,
                savourrpc.market_pb2.SymbolPriceResponse,
            ),
            '/savourrpc.market.PriceService/getStableCoins': grpclib.const.Handler(
                self.getStableCoins,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.market_pb2.StableCoinRequest,
                savourrpc.market_pb2.StableCoinResponse,
            ),
            '/savourrpc.market.PriceService/getStableCoinPrice': grpclib.const.Handler(
                self.getStableCoinPrice,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.market_pb2.StableCoinPriceRequest,
                savourrpc.market_pb2.StableCoinPriceResponse,
            ),
        }


class PriceServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.getExchanges = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.market.PriceService/getExchanges',
            savourrpc.market_pb2.ExchangeRequest,
            savourrpc.market_pb2.ExchangeResponse,
        )
        self.getAssets = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.market.PriceService/getAssets',
            savourrpc.market_pb2.AssetRequest,
            savourrpc.market_pb2.AssetResponse,
        )
        self.getSymbols = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.market.PriceService/getSymbols',
            savourrpc.market_pb2.SymbolRequest,
            savourrpc.market_pb2.SymbolResponse,
        )
        self.getSymbolPrices = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.market.PriceService/getSymbolPrices',
            savourrpc.market_pb2.SymbolPriceRequest,
            savourrpc.market_pb2.SymbolPriceResponse,
        )
        self.getStableCoins = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.market.PriceService/getStableCoins',
            savourrpc.market_pb2.StableCoinRequest,
            savourrpc.market_pb2.StableCoinResponse,
        )
        self.getStableCoinPrice = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.market.PriceService/getStableCoinPrice',
            savourrpc.market_pb2.StableCoinPriceRequest,
            savourrpc.market_pb2.StableCoinPriceResponse,
        )
