# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: savourrpc/wallet.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import savourrpc.common_pb2
import savourrpc.wallet_pb2


class WalletServiceBase(abc.ABC):

    @abc.abstractmethod
    async def getSupportCoins(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.SupportCoinsRequest, savourrpc.wallet_pb2.SupportCoinsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def convertAddress(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.ConvertAddressRequest, savourrpc.wallet_pb2.ConvertAddressResponse]') -> None:
        pass

    @abc.abstractmethod
    async def validAddress(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.ValidAddressRequest, savourrpc.wallet_pb2.ValidAddressResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getBlock(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.BlockRequest, savourrpc.wallet_pb2.BlockResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getNonce(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.NonceRequest, savourrpc.wallet_pb2.NonceResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getGasPrice(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.GasPriceRequest, savourrpc.wallet_pb2.GasPriceResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getBalance(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.BalanceRequest, savourrpc.wallet_pb2.BalanceResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getAccount(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.AccountRequest, savourrpc.wallet_pb2.AccountResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getMinRent(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.MinRentRequest, savourrpc.wallet_pb2.MinRentResponse]') -> None:
        pass

    @abc.abstractmethod
    async def SendTx(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.SendTxRequest, savourrpc.wallet_pb2.SendTxResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getTxByAddress(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.TxAddressRequest, savourrpc.wallet_pb2.TxAddressResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getTxByHash(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.TxHashRequest, savourrpc.wallet_pb2.TxHashResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getUtxo(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.UtxoRequest, savourrpc.wallet_pb2.UtxoResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getUnspentOutputs(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.UnspentOutputsRequest, savourrpc.wallet_pb2.UnspentOutputsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getUtxoInsFromData(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.UtxoInsFromDataRequest, savourrpc.wallet_pb2.UtxoInsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getAccountTxFromData(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.TxFromDataRequest, savourrpc.wallet_pb2.AccountTxResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getUtxoTxFromData(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.TxFromDataRequest, savourrpc.wallet_pb2.UtxoTxResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getAccountTxFromSignedData(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.TxFromSignedDataRequest, savourrpc.wallet_pb2.AccountTxResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetUtxoTxFromSignedData(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.TxFromSignedDataRequest, savourrpc.wallet_pb2.UtxoTxResponse]') -> None:
        pass

    @abc.abstractmethod
    async def createAccountSignedTx(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.CreateAccountSignedTxRequest, savourrpc.wallet_pb2.CreateSignedTxResponse]') -> None:
        pass

    @abc.abstractmethod
    async def createAccountTx(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.CreateAccountTxRequest, savourrpc.wallet_pb2.CreateAccountTxResponse]') -> None:
        pass

    @abc.abstractmethod
    async def createUtxoSignedTx(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.CreateUtxoSignedTxRequest, savourrpc.wallet_pb2.CreateSignedTxResponse]') -> None:
        pass

    @abc.abstractmethod
    async def createUtxoTx(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.CreateUtxoTxRequest, savourrpc.wallet_pb2.CreateUtxoTxResponse]') -> None:
        pass

    @abc.abstractmethod
    async def verifyAccountSignedTx(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.VerifySignedTxRequest, savourrpc.wallet_pb2.VerifySignedTxResponse]') -> None:
        pass

    @abc.abstractmethod
    async def verifyUtxoSignedTx(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.VerifySignedTxRequest, savourrpc.wallet_pb2.VerifySignedTxResponse]') -> None:
        pass

    @abc.abstractmethod
    async def ABIBinToJSON(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.ABIBinToJSONRequest, savourrpc.wallet_pb2.ABIBinToJSONResponse]') -> None:
        pass

    @abc.abstractmethod
    async def ABIJSONToBin(self, stream: 'grpclib.server.Stream[savourrpc.wallet_pb2.ABIJSONToBinRequest, savourrpc.wallet_pb2.ABIJSONToBinResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/savourrpc.wallet.WalletService/getSupportCoins': grpclib.const.Handler(
                self.getSupportCoins,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.SupportCoinsRequest,
                savourrpc.wallet_pb2.SupportCoinsResponse,
            ),
            '/savourrpc.wallet.WalletService/convertAddress': grpclib.const.Handler(
                self.convertAddress,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.ConvertAddressRequest,
                savourrpc.wallet_pb2.ConvertAddressResponse,
            ),
            '/savourrpc.wallet.WalletService/validAddress': grpclib.const.Handler(
                self.validAddress,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.ValidAddressRequest,
                savourrpc.wallet_pb2.ValidAddressResponse,
            ),
            '/savourrpc.wallet.WalletService/getBlock': grpclib.const.Handler(
                self.getBlock,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.BlockRequest,
                savourrpc.wallet_pb2.BlockResponse,
            ),
            '/savourrpc.wallet.WalletService/getNonce': grpclib.const.Handler(
                self.getNonce,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.NonceRequest,
                savourrpc.wallet_pb2.NonceResponse,
            ),
            '/savourrpc.wallet.WalletService/getGasPrice': grpclib.const.Handler(
                self.getGasPrice,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.GasPriceRequest,
                savourrpc.wallet_pb2.GasPriceResponse,
            ),
            '/savourrpc.wallet.WalletService/getBalance': grpclib.const.Handler(
                self.getBalance,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.BalanceRequest,
                savourrpc.wallet_pb2.BalanceResponse,
            ),
            '/savourrpc.wallet.WalletService/getAccount': grpclib.const.Handler(
                self.getAccount,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.AccountRequest,
                savourrpc.wallet_pb2.AccountResponse,
            ),
            '/savourrpc.wallet.WalletService/getMinRent': grpclib.const.Handler(
                self.getMinRent,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.MinRentRequest,
                savourrpc.wallet_pb2.MinRentResponse,
            ),
            '/savourrpc.wallet.WalletService/SendTx': grpclib.const.Handler(
                self.SendTx,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.SendTxRequest,
                savourrpc.wallet_pb2.SendTxResponse,
            ),
            '/savourrpc.wallet.WalletService/getTxByAddress': grpclib.const.Handler(
                self.getTxByAddress,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.TxAddressRequest,
                savourrpc.wallet_pb2.TxAddressResponse,
            ),
            '/savourrpc.wallet.WalletService/getTxByHash': grpclib.const.Handler(
                self.getTxByHash,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.TxHashRequest,
                savourrpc.wallet_pb2.TxHashResponse,
            ),
            '/savourrpc.wallet.WalletService/getUtxo': grpclib.const.Handler(
                self.getUtxo,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.UtxoRequest,
                savourrpc.wallet_pb2.UtxoResponse,
            ),
            '/savourrpc.wallet.WalletService/getUnspentOutputs': grpclib.const.Handler(
                self.getUnspentOutputs,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.UnspentOutputsRequest,
                savourrpc.wallet_pb2.UnspentOutputsResponse,
            ),
            '/savourrpc.wallet.WalletService/getUtxoInsFromData': grpclib.const.Handler(
                self.getUtxoInsFromData,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.UtxoInsFromDataRequest,
                savourrpc.wallet_pb2.UtxoInsResponse,
            ),
            '/savourrpc.wallet.WalletService/getAccountTxFromData': grpclib.const.Handler(
                self.getAccountTxFromData,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.TxFromDataRequest,
                savourrpc.wallet_pb2.AccountTxResponse,
            ),
            '/savourrpc.wallet.WalletService/getUtxoTxFromData': grpclib.const.Handler(
                self.getUtxoTxFromData,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.TxFromDataRequest,
                savourrpc.wallet_pb2.UtxoTxResponse,
            ),
            '/savourrpc.wallet.WalletService/getAccountTxFromSignedData': grpclib.const.Handler(
                self.getAccountTxFromSignedData,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.TxFromSignedDataRequest,
                savourrpc.wallet_pb2.AccountTxResponse,
            ),
            '/savourrpc.wallet.WalletService/GetUtxoTxFromSignedData': grpclib.const.Handler(
                self.GetUtxoTxFromSignedData,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.TxFromSignedDataRequest,
                savourrpc.wallet_pb2.UtxoTxResponse,
            ),
            '/savourrpc.wallet.WalletService/createAccountSignedTx': grpclib.const.Handler(
                self.createAccountSignedTx,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.CreateAccountSignedTxRequest,
                savourrpc.wallet_pb2.CreateSignedTxResponse,
            ),
            '/savourrpc.wallet.WalletService/createAccountTx': grpclib.const.Handler(
                self.createAccountTx,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.CreateAccountTxRequest,
                savourrpc.wallet_pb2.CreateAccountTxResponse,
            ),
            '/savourrpc.wallet.WalletService/createUtxoSignedTx': grpclib.const.Handler(
                self.createUtxoSignedTx,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.CreateUtxoSignedTxRequest,
                savourrpc.wallet_pb2.CreateSignedTxResponse,
            ),
            '/savourrpc.wallet.WalletService/createUtxoTx': grpclib.const.Handler(
                self.createUtxoTx,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.CreateUtxoTxRequest,
                savourrpc.wallet_pb2.CreateUtxoTxResponse,
            ),
            '/savourrpc.wallet.WalletService/verifyAccountSignedTx': grpclib.const.Handler(
                self.verifyAccountSignedTx,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.VerifySignedTxRequest,
                savourrpc.wallet_pb2.VerifySignedTxResponse,
            ),
            '/savourrpc.wallet.WalletService/verifyUtxoSignedTx': grpclib.const.Handler(
                self.verifyUtxoSignedTx,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.VerifySignedTxRequest,
                savourrpc.wallet_pb2.VerifySignedTxResponse,
            ),
            '/savourrpc.wallet.WalletService/ABIBinToJSON': grpclib.const.Handler(
                self.ABIBinToJSON,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.ABIBinToJSONRequest,
                savourrpc.wallet_pb2.ABIBinToJSONResponse,
            ),
            '/savourrpc.wallet.WalletService/ABIJSONToBin': grpclib.const.Handler(
                self.ABIJSONToBin,
                grpclib.const.Cardinality.UNARY_UNARY,
                savourrpc.wallet_pb2.ABIJSONToBinRequest,
                savourrpc.wallet_pb2.ABIJSONToBinResponse,
            ),
        }


class WalletServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.getSupportCoins = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/getSupportCoins',
            savourrpc.wallet_pb2.SupportCoinsRequest,
            savourrpc.wallet_pb2.SupportCoinsResponse,
        )
        self.convertAddress = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/convertAddress',
            savourrpc.wallet_pb2.ConvertAddressRequest,
            savourrpc.wallet_pb2.ConvertAddressResponse,
        )
        self.validAddress = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/validAddress',
            savourrpc.wallet_pb2.ValidAddressRequest,
            savourrpc.wallet_pb2.ValidAddressResponse,
        )
        self.getBlock = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/getBlock',
            savourrpc.wallet_pb2.BlockRequest,
            savourrpc.wallet_pb2.BlockResponse,
        )
        self.getNonce = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/getNonce',
            savourrpc.wallet_pb2.NonceRequest,
            savourrpc.wallet_pb2.NonceResponse,
        )
        self.getGasPrice = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/getGasPrice',
            savourrpc.wallet_pb2.GasPriceRequest,
            savourrpc.wallet_pb2.GasPriceResponse,
        )
        self.getBalance = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/getBalance',
            savourrpc.wallet_pb2.BalanceRequest,
            savourrpc.wallet_pb2.BalanceResponse,
        )
        self.getAccount = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/getAccount',
            savourrpc.wallet_pb2.AccountRequest,
            savourrpc.wallet_pb2.AccountResponse,
        )
        self.getMinRent = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/getMinRent',
            savourrpc.wallet_pb2.MinRentRequest,
            savourrpc.wallet_pb2.MinRentResponse,
        )
        self.SendTx = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/SendTx',
            savourrpc.wallet_pb2.SendTxRequest,
            savourrpc.wallet_pb2.SendTxResponse,
        )
        self.getTxByAddress = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/getTxByAddress',
            savourrpc.wallet_pb2.TxAddressRequest,
            savourrpc.wallet_pb2.TxAddressResponse,
        )
        self.getTxByHash = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/getTxByHash',
            savourrpc.wallet_pb2.TxHashRequest,
            savourrpc.wallet_pb2.TxHashResponse,
        )
        self.getUtxo = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/getUtxo',
            savourrpc.wallet_pb2.UtxoRequest,
            savourrpc.wallet_pb2.UtxoResponse,
        )
        self.getUnspentOutputs = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/getUnspentOutputs',
            savourrpc.wallet_pb2.UnspentOutputsRequest,
            savourrpc.wallet_pb2.UnspentOutputsResponse,
        )
        self.getUtxoInsFromData = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/getUtxoInsFromData',
            savourrpc.wallet_pb2.UtxoInsFromDataRequest,
            savourrpc.wallet_pb2.UtxoInsResponse,
        )
        self.getAccountTxFromData = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/getAccountTxFromData',
            savourrpc.wallet_pb2.TxFromDataRequest,
            savourrpc.wallet_pb2.AccountTxResponse,
        )
        self.getUtxoTxFromData = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/getUtxoTxFromData',
            savourrpc.wallet_pb2.TxFromDataRequest,
            savourrpc.wallet_pb2.UtxoTxResponse,
        )
        self.getAccountTxFromSignedData = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/getAccountTxFromSignedData',
            savourrpc.wallet_pb2.TxFromSignedDataRequest,
            savourrpc.wallet_pb2.AccountTxResponse,
        )
        self.GetUtxoTxFromSignedData = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/GetUtxoTxFromSignedData',
            savourrpc.wallet_pb2.TxFromSignedDataRequest,
            savourrpc.wallet_pb2.UtxoTxResponse,
        )
        self.createAccountSignedTx = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/createAccountSignedTx',
            savourrpc.wallet_pb2.CreateAccountSignedTxRequest,
            savourrpc.wallet_pb2.CreateSignedTxResponse,
        )
        self.createAccountTx = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/createAccountTx',
            savourrpc.wallet_pb2.CreateAccountTxRequest,
            savourrpc.wallet_pb2.CreateAccountTxResponse,
        )
        self.createUtxoSignedTx = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/createUtxoSignedTx',
            savourrpc.wallet_pb2.CreateUtxoSignedTxRequest,
            savourrpc.wallet_pb2.CreateSignedTxResponse,
        )
        self.createUtxoTx = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/createUtxoTx',
            savourrpc.wallet_pb2.CreateUtxoTxRequest,
            savourrpc.wallet_pb2.CreateUtxoTxResponse,
        )
        self.verifyAccountSignedTx = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/verifyAccountSignedTx',
            savourrpc.wallet_pb2.VerifySignedTxRequest,
            savourrpc.wallet_pb2.VerifySignedTxResponse,
        )
        self.verifyUtxoSignedTx = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/verifyUtxoSignedTx',
            savourrpc.wallet_pb2.VerifySignedTxRequest,
            savourrpc.wallet_pb2.VerifySignedTxResponse,
        )
        self.ABIBinToJSON = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/ABIBinToJSON',
            savourrpc.wallet_pb2.ABIBinToJSONRequest,
            savourrpc.wallet_pb2.ABIBinToJSONResponse,
        )
        self.ABIJSONToBin = grpclib.client.UnaryUnaryMethod(
            channel,
            '/savourrpc.wallet.WalletService/ABIJSONToBin',
            savourrpc.wallet_pb2.ABIJSONToBinRequest,
            savourrpc.wallet_pb2.ABIJSONToBinResponse,
        )
