# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from savourrpc import wallet_pb2 as savourrpc_dot_wallet__pb2


class WalletServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getSupportCoins = channel.unary_unary(
                '/savourrpc.wallet.WalletService/getSupportCoins',
                request_serializer=savourrpc_dot_wallet__pb2.SupportCoinsRequest.SerializeToString,
                response_deserializer=savourrpc_dot_wallet__pb2.SupportCoinsResponse.FromString,
                )
        self.SendTx = channel.unary_unary(
                '/savourrpc.wallet.WalletService/SendTx',
                request_serializer=savourrpc_dot_wallet__pb2.SendTxRequest.SerializeToString,
                response_deserializer=savourrpc_dot_wallet__pb2.SendTxResponse.FromString,
                )


class WalletServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getSupportCoins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WalletServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getSupportCoins': grpc.unary_unary_rpc_method_handler(
                    servicer.getSupportCoins,
                    request_deserializer=savourrpc_dot_wallet__pb2.SupportCoinsRequest.FromString,
                    response_serializer=savourrpc_dot_wallet__pb2.SupportCoinsResponse.SerializeToString,
            ),
            'SendTx': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTx,
                    request_deserializer=savourrpc_dot_wallet__pb2.SendTxRequest.FromString,
                    response_serializer=savourrpc_dot_wallet__pb2.SendTxResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'savourrpc.wallet.WalletService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WalletService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getSupportCoins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/savourrpc.wallet.WalletService/getSupportCoins',
            savourrpc_dot_wallet__pb2.SupportCoinsRequest.SerializeToString,
            savourrpc_dot_wallet__pb2.SupportCoinsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendTx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/savourrpc.wallet.WalletService/SendTx',
            savourrpc_dot_wallet__pb2.SendTxRequest.SerializeToString,
            savourrpc_dot_wallet__pb2.SendTxResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
